name: instaastro_clone
description: A clone of the InstaAstro app with user and astrologer applications.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # State management
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.1.5
  # Navigation
  go_router: ^10.1.2
  # Network and API
  dio: ^5.3.2
  json_annotation: ^4.8.1
  # Authentication
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^6.0.1
  # Real-time communication
  agora_rtc_engine: ^6.2.2
  # Payment integration
  razorpay_flutter: ^1.3.5
  # Local storage
  shared_preferences: ^2.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # UI components
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  intl: ^0.18.1
  # Notifications
  firebase_messaging: ^14.6.7
  flutter_local_notifications: ^15.1.1
  # Location
  geolocator: ^10.0.1
  geocoding: ^2.1.0
  # Others
  uuid: ^3.0.7
  path_provider: ^2.1.1
  permission_handler: ^10.4.3
  url_launcher: ^6.1.14
  image_picker: ^1.0.4
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
